enabled: true
version: "4.0.1"
imageName: "docker.art.lmru.tech/bricks/ingress-autoswagger"
refreshCron: "@every 1m"
ingressPath: "/"
discoveringVersion:
  - v2
  - v3
discoveringApidocsExtension: ""
